### PR TITLE
fix(dotnet): replace non-existent RegisterObservableCallback with cor…

### LINKED ISSUE #10830: [Docs] .NET Metrics: RegisterObservableCallback does not exist in the API
### What needs to be changed?

The [Batching observable measurements](https://opentelemetry.io/docs/languages/dotnet/metrics/instruments/#batching-observable-measurements) section of the OpenTelemetry .NET Metrics documentation references a method meter.RegisterObservableCallback(...), which does not appear to exist in the .NET Metrics API.

Impact

Users following the documentation will encounter a compilation error when attempting to use RegisterObservableCallback, leading to confusion and loss of trust in the documentation.

Steps to reproduce

Navigate to the [Batching observable measurements](https://opentelemetry.io/docs/languages/dotnet/metrics/instruments/#batching-observable-measurements) section.
Copy the provided code example using meter.RegisterObservableCallback(...).
Attempt to compile — the method does not exist.
Expected behavior

The documentation should reference a valid, existing API method, or the code example should be corrected or removed.

Related links

https://opentelemetry.io/docs/languages/dotnet/metrics/instruments/#batching-observable-measurements
https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation

### Name + path of the page

https://opentelemetry.io/docs/languages/dotnet/metrics/instruments/#batching-observable-measurements

### Additional context

Hej!

While reading the documentation I came up to a method which does not exist in .Net 10 Metrics class.

Could you lead me to the source of this method, or if it even exists anymore?
I tried everything to find it but not luck.

Thanks 
Greetings

PS. Parts of the ticket were generated by you KI bot on the docs webpage

### PR DESCRIPTION
**Pull request by AtharvaKatiyar**
fix(dotnet): replace non-existent RegisterObservableCallback with correct IEnumerable<Measurement<T>> pattern

- [x] I have read and followed the [Contributing](https://opentelemetry.io/docs/contributing/) docs, especially the "**First-time contributing?**" section.
- [x] This PR has content that I did not fully write myself.
  - [x] I used AI and I have read and followed the [Generative AI Contribution Policy](https://github.com/open-telemetry/community/blob/main/policies/genai.md).
- [ ] I have the experience and knowledge necessary to understand, review, and validate all content in this PR.[^I-know-my-stuff]

[^I-know-my-stuff]:
    Yes, I can answer maintainer questions about the content of this PR, without using AI.

---

Fixes #10830

The **Batching observable measurements** section in the .NET Metrics instruments documentation referenced `meter.RegisterObservableCallback(...)`, which does not exist in the `System.Diagnostics.Metrics` API. Anyone copying that example would get a compilation error.

**Fix:** Replaced the invalid example with the correct .NET idiomatic pattern — passing a callback that returns `IEnumerable<Measurement<T>>` directly to each `CreateObservable*` method. This is how .NET actually supports reporting multiple measurements per collection cycle.

**Before (broken):**
```csharp
meter.RegisterObservableCallback(observableInstruments =>
{
    observableInstruments.Observe(observableCounter, 42, new("type", "product_a"));
    observableInstruments.Observe(observableGauge, 12.3, new("resource", "cpu"));
}, observableCounter, observableGauge);

**After (correct):**

```csharp
meter.CreateObservableCounter<long>(
    "my_observable_counter",
    () => new[]
    {
        new Measurement<long>(42, new KeyValuePair<string, object?>("type", "product_a")),
        new Measurement<long>(17, new KeyValuePair<string, object?>("type", "product_b")),
    },
    "items",
    "Total number of processed items by product type");

References:

Fixes: #10830
.NET Meter API: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics.meter

### CODE REVIEW

**Comment by martincostello** [comment]
I'm curious where `RegisterObservableCallback()` even came from in the first place.

**Comment by AtharvaKatiyar** [comment]
> I'm curious where `RegisterObservableCallback()` even came from in the first place.

It was introduced in PR #7474 (commit bb92749), which migrated .NET docs into this site. The method doesn't exist in the System.Diagnostics.Metrics Meter class in any .NET version, so it was never a valid API reference. This PR replaces it with the correct pattern of returning IEnumerable<Measurement<T>> from the callback passed directly to CreateObservable*.

**Comment by martincostello** [comment]
Yes, but where did _that_ come from?

That PR added it, saying it came from the documentation in the .NET SDK repo, but I can't find any reference to it anywhere.

**Comment by AtharvaKatiyar** [comment]
> Yes, but where did _that_ come from?
> 
> That PR added it, saying it came from the documentation in the .NET SDK repo, but I can't find any reference to it anywhere.

Looking at PR #7474, the author (@theletterf) explicitly states they "leveraged Copilot to set up the structure, reading the Markdown files and code examples" from the opentelemetry-dotnet/docs folder. The method doesn't appear to exist in that source repo either — a search of open-telemetry/opentelemetry-dotnet returns no results for RegisterObservableCallback. It was most likely generated by Copilot during that process and wasn't caught in review, since the concept it describes (batching observable measurements) is valid, just implemented completely differently in .NET. The correct approach is returning IEnumerable<Measurement<T>> from the callback passed directly to CreateObservable*, which is what this PR fixes.

File: content/en/docs/languages/dotnet/metrics/instruments.md [hunk 1]
```diff
@@ -145,22 +145,37 @@ meter.CreateObservableGauge("cpu_usage", () =>
...
-var observableCounter = meter.CreateObservableCounter<long>("my_observable_counter", "items");
-var observableGauge = meter.CreateObservableGauge<double>("my_observable_gauge", "%");
+using System.Diagnostics.Metrics;
 
-meter.RegisterObservableCallback(observableInstruments =>
-{
-    // Record a value for the counter
-    observableInstruments.Observe(observableCounter, 42, new("type", "product_a"));
+// Create a meter
+var meter = new Meter("MyCompany.MyProduct", "1.0.0");
```
Comment (martincostello) [inline content/en/docs/languages/dotnet/metrics/instruments.md]:
```suggestion
using var meter = new Meter("MyCompany.MyProduct", "1.0.0");
```

File: content/en/docs/languages/dotnet/metrics/instruments.md [hunk 2]
```diff
@@ -145,22 +145,37 @@ meter.CreateObservableGauge("cpu_usage", () =>
...
 
-    // Record a value for the gauge
-    observableInstruments.Observe(observableGauge, 12.3, new("resource", "cpu"));
-}, observableCounter, observableGauge);
+// Observable counter reporting multiple measurements per collection
+meter.CreateObservableCounter<long>(
```
Comment (martincostello) [inline content/en/docs/languages/dotnet/metrics/instruments.md]:
```suggestion
meter.CreateObservableCounter(
```

File: content/en/docs/languages/dotnet/metrics/instruments.md [hunk 3]
```diff
@@ -145,22 +145,37 @@ meter.CreateObservableGauge("cpu_usage", () =>
...
+    () => new[]
+    {
+        new Measurement<long>(42, new KeyValuePair<string, object?>("type", "product_a")),
+        new Measurement<long>(17, new KeyValuePair<string, object?>("type", "product_b")),
+    },
+    "items",
+    "Total number of processed items by product type");
+
+// Observable gauge reporting multiple measurements per collection
+meter.CreateObservableGauge<double>(
```
Comment (martincostello) [inline content/en/docs/languages/dotnet/metrics/instruments.md]:
```suggestion
meter.CreateObservableGauge(
```

**Review by martincostello — COMMENTED** [review]
I pasted the code into an IDE to check it compiled and it had 3 green squiggles.

**Review by martincostello — APPROVED** [review]

**Comment by AtharvaKatiyar** [comment]
Thanks for catching those! Applied all three suggestions. Should have caught the using var disposal and the redundant type args before submitting — noted for next time.

File: content/en/docs/languages/dotnet/metrics/instruments.md [hunk 4]
```diff
@@ -145,22 +145,37 @@ meter.CreateObservableGauge("cpu_usage", () =>
 
 ## Batching observable measurements
 
-You can also register a callback that returns multiple measurements for multiple
-instruments:
+Each observable instrument accepts a callback that can return multiple
```
Comment (cijothomas) [inline content/en/docs/languages/dotnet/metrics/instruments.md]: I am not sure why we need this section at all. The original intend was likely to show that callbacks can report metrics for multiple instruments inside single callback. Such capability do not exist today, so why have this section at all? Reporting multiple measurements for the same instrument/callback - it's already shown in existing docs. (line 124-132 for ObservableUpdownCounter shows this)

**Review by cijothomas — CHANGES_REQUESTED** [review]
Thanks for catching the issue! I wonder how it got added to the doc and survived for so long. It might require some analysis.

Requisting changes as I don't think the section itself is relevant and better to remove it entirely, than duplicating existing information.

**Comment by AtharvaKatiyar** [comment]
@cijothomas 
You're absolutely right. ObservableUpDownCounter already demonstrates this pattern clearly and the separate section is redundant. I've removed the section entirely. Thanks again for the review!

**Comment by martincostello** [comment]
Sounds like you're an AI Agent, and not a human. It is against the [OpenTelemetry AI policy](https://github.com/open-telemetry/community/blob/main/policies/genai.md) to respond to comments as such.

**Comment by AtharvaKatiyar** [comment]
> Sounds like you're an AI Agent, and not a human. It is against the [OpenTelemetry AI policy](https://github.com/open-telemetry/community/blob/main/policies/genai.md) to respond to comments as such.

Do not worry. I am a real person and i will make sure to reply properly.

**Comment by Chaosflo** [comment]
Thanks, for investigating where this is comes from and fixing the docs! 
I spent 2 hours finding the method = ) 

At least I am not crazy 
Greetings

**Comment by theletterf** [comment]
@AtharvaKatiyar While the contribution might hold some value, we require that everyone who contributes has sufficient knowledge to explain the changes, as stated in our PR template:

> I have the experience and knowledge necessary to understand, review, and validate all content in this PR

This, coupled with a violation of our policies, makes me lean towards closing the present PR. We're open to more contributions provided they'll follow our [guidelines](https://opentelemetry.io/docs/contributing/pull-requests/#using-ai).

Thanks for your understanding.
